version: '3.8'
services:
  fpl-price-check02:
    build: .
    container_name: fpl-price-check02
    volumes:
      - /volume1/docker/portainer/portainer_data/fpl-price-change/fpl_snapshots:/app/fpl_snapshots
      - /volume1/docker/portainer/portainer_data/fpl-price-change/logs:/app/logs
    restart: unless-stopped
